// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NullableUnitGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CodeTemplate : CodeTemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n// <auto-generated>\n// THIS (.cs) FILE IS GENERATED BY NullableUnitGenerator. DO" +
                    " NOT CHANGE IT.\n// </auto-generated>\n#pragma warning disable CS8669\nusing System" +
                    ";\n");
 if (HasFlag(UnitGenerateOptions.MessagePackFormatter)) { 
            this.Write(" \nusing MessagePack;\nusing MessagePack.Formatters;\n");
 } 
            this.Write("\n");
 if (HasFlag(UnitGenerateOptions.JsonConverter)) { 
            this.Write(" \nusing System.Text.Json;\nusing System.Text.Json.Serialization;\n");
 } 
            this.Write("\n");
 if (HasFlag(UnitGenerateOptions.DapperTypeHandler)) { 
            this.Write(" \nusing System.Runtime.CompilerServices;\n");
 } 
            this.Write("\n\n");
 if (!string.IsNullOrEmpty(Namespace)) { 
            this.Write("\nnamespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            this.Write("\n{\n");
 } 
            this.Write("\n");
 if (HasFlag(UnitGenerateOptions.JsonConverter)) { 
            this.Write(" \n    [JsonConverter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("JsonConverter))]\n");
 } 
            this.Write("\n");
 if (HasFlag(UnitGenerateOptions.MessagePackFormatter)) { 
            this.Write(" \n    [MessagePackFormatter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("MessagePackFormatter))]\n");
 } 
            this.Write("\n    [System.ComponentModel.TypeConverter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("TypeConverter))]\n    readonly partial struct ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" : IEquatable<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("> ");
            this.Write(this.ToStringHelper.ToStringWithCulture(HasFlag(UnitGenerateOptions.Comparable) ? $", IComparable<{Name}>" : ""));
            this.Write("\n    {\n        readonly ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" value;\n\n        public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" AsPrimitive() => value;\n\n        public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" value)\n        {\n            this.value = value;\n");
 if (HasFlag(UnitGenerateOptions.Validate)) { 
            this.Write(" \n            this.Validate();\n");
 } 
            this.Write("\n        }\n\n");
 if (HasFlag(UnitGenerateOptions.Validate)) { 
            this.Write(" \n        private partial void Validate();\n");
 } 
            this.Write("\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(HasFlag(UnitGenerateOptions.ImplicitOperator) ? "implicit" : "explicit"));
            this.Write(" operator ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value)\n        {\n            return value.value;\n        }\n\n        public stati" +
                    "c ");
            this.Write(this.ToStringHelper.ToStringWithCulture(HasFlag(UnitGenerateOptions.ImplicitOperator) ? "implicit" : "explicit"));
            this.Write(" operator ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" value)\n        {\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(value);\n        }\n\n        public bool Equals(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" other)\n        {\n            return value.Equals(other.value);\n        }\n\n      " +
                    "  public override bool Equals(object obj)\n        {\n            if (obj == null)" +
                    " return false;\n            var t = obj.GetType();\n            if (t == typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("))\n            {\n                return Equals((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(")obj);\n            }\n            if (t == typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write("))\n            {\n                return value.Equals((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")obj);\n            }\n\n            return value.Equals(obj);\n        }\n\n        pu" +
                    "blic override int GetHashCode()\n        {\n            return value.GetHashCode()" +
                    ";\n        }\n\n        public override string ToString()\n        {\n");
 if (ToStringFormat == null) { 
            this.Write("\n            return value.ToString();\n");
 } else { 
            this.Write("\n            return string.Format(\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(ToStringFormat));
            this.Write("\", value);\n");
 } 
            this.Write("\n        }\n\n        public static bool operator ==(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\n        {\n            return x.value.Equals(y.value);\n        }\n\n        publ" +
                    "ic static bool operator !=(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\n        {\n            return !x.value.Equals(y.value);\n        }\n\n");
 if (Type == "Guid" || Type == "System.Guid") { 
            this.Write("\n        public static readonly ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Empty = default(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(");\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" New()\n        {\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Guid.NewGuid());\n        }\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" New");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("()\n        {\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Guid.NewGuid());\n        }\n\n");
 } 
            this.Write("\n\n");
 if (Type == "Ulid" || Type == "System.Ulid") { 
            this.Write("\n        public static readonly ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Empty = default(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(");\n        \n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" New()\n        {\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Ulid.NewUlid());\n        }\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" New");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("()\n        {\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Ulid.NewUlid());\n        }\n\n");
 } 
            this.Write("\n\n");
 if (HasFlag(UnitGenerateOptions.ParseMethod)) { 
            this.Write(" \n        // UnitGenerateOptions.ParseMethod\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Parse(string s)\n        {\n");
 if (Type == "string") { 
            this.Write("\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(s);\n");
 } else { 
            this.Write("\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".Parse(s));\n");
 } 
            this.Write("\n        }\n        \n        public static bool TryParse(string s, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result)\n        {\n");
 if (Type == "string") { 
            this.Write("\n            try\n            {\n                result = Parse(s);    \n           " +
                    "     return true;\n            } \n            catch \n            {\n              " +
                    "  result = default;\n                return false;\n            }\n");
 } else { 
            this.Write("\n            if(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".TryParse(s, out var r))\n            {\n                result = new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(r);\n                return true;\n            }\n            else\n            {\n  " +
                    "              result = default(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(");\n                return false;\n            }\n");
 } 
            this.Write("\n        }\n\n");
 } 
            this.Write("\n\n");
 if (HasFlag(UnitGenerateOptions.MinMaxMethod)) { 
            this.Write(" \n        // UnitGenerateOptions.MinMaxMethod\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Min(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\n        {\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Math.Min(x.value, y.value));\n        }\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Max(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\n        {\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Math.Max(x.value, y.value));\n        }\n\n");
 } 
            this.Write("\n\n");
 if (Type == "bool") { 
            this.Write("\n        // Default\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" operator true(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\n        {\n            return x.value;\n        }\n        \n        public stati" +
                    "c ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" operator false(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\n        {\n            return !x.value;\n        }\n        \n        public stat" +
                    "ic ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" operator !(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\n        {\n            return !x.value;\n        }\n\n");
 } 
            this.Write("\n\n");
 if (HasFlag(UnitGenerateOptions.ArithmeticOperator)) { 
            this.Write(" \n        // UnitGenerateOptions.ArithmeticOperator\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator +(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\n        {\n            checked\n            {\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value + y.value));\n            }\n        }\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator -(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\n        {\n            checked\n            {\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value - y.value));\n            }\n        }\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator *(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\n        {\n            checked\n            {\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value * y.value));\n            }\n        }\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator /(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\n        {\n            checked\n            {\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value / y.value));\n            }\n        }\n\n");
 } 
            this.Write("\n\n");
 if (HasFlag(UnitGenerateOptions.ValueArithmeticOperator)) { 
            this.Write(" \n        // UnitGenerateOptions.ValueArithmeticOperator\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator ++(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\n        {\n            checked\n            {\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value + 1));\n            }\n        }\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator --(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\n        {\n            checked\n            {\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value - 1));\n            }\n        }\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator +(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" y)\n        {\n            checked\n            {\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value + y));\n            }\n        }\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator -(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" y)\n        {\n            checked\n            {\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value - y));\n            }\n        }\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator *(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" y)\n        {\n            checked\n            {\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value * y));\n            }\n        }\n\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator /(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" y)\n        {\n            checked\n            {\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value / y));\n            }\n        }\n\n");
 } 
            this.Write("\n\n");
 if (HasFlag(UnitGenerateOptions.Comparable)) { 
            this.Write(" \n        // UnitGenerateOptions.Comparable\n\n        public int CompareTo(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" other)\n        {\n            return value.CompareTo(other.value);\n        }\n\n");
 if (!HasFlag(UnitGenerateOptions.WithoutComparisonOperator)) { 
            this.Write("         \n        \n        public static bool operator >(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\n        {\n            return x.value > y.value;\n        }\n\n        public sta" +
                    "tic bool operator <(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\n        {\n            return x.value < y.value;\n        }\n\n        public sta" +
                    "tic bool operator >=(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\n        {\n            return x.value >= y.value;\n        }\n\n        public st" +
                    "atic bool operator <=(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\n        {\n            return x.value <= y.value;\n        }\n");
 } 
            this.Write("\n\n");
 } 
            this.Write("\n\n");
 if (HasFlag(UnitGenerateOptions.JsonConverter)) { 
            this.Write(" \n        // UnitGenerateOptions.JsonConverter\n        private class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("JsonConverter : JsonConverter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(">\n        {\n            public override void Write(Utf8JsonWriter writer, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value, JsonSerializerOptions options)\n            {\n                var converte" +
                    "r = options.GetConverter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")) as JsonConverter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(">;\n                if (converter != null)\n                {\n                    c" +
                    "onverter.Write(writer, value.value, options);\n                }\n                " +
                    "else\n                {\n                    throw new JsonException($\"{typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")} converter does not found.\");\n                }\n            }\n        \n        " +
                    "    public override ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions option" +
                    "s)\n            {\n                var converter = options.GetConverter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")) as JsonConverter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(">;\n                if (converter != null)\n                {\n                    r" +
                    "eturn new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(converter.Read(ref reader, typeToConvert, options));\n                }\n         " +
                    "       else\n                {\n                    throw new JsonException($\"{typ" +
                    "eof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")} converter does not found.\");\n                }\n            }\n\n");
if (HasFlag(UnitGenerateOptions.JsonConverterDictionaryKeySupport)) {  
            this.Write("\n            public override void WriteAsPropertyName(Utf8JsonWriter writer, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value, JsonSerializerOptions options)\n            {\n");
if (IsSupportUtf8Formatter()) {  
            this.Write(@"
                Span<byte> buffer = stackalloc byte[36];
                if (System.Buffers.Text.Utf8Formatter.TryFormat(value.value, buffer, out var written))
                {
                    writer.WritePropertyName(buffer.Slice(0, written));
                }
                else
                {
                    writer.WritePropertyName(value.value.ToString());
                }
");
 } else if (IsUlid()) { 
            this.Write("\n                writer.WritePropertyName(value.value.ToString());\n");
 } else { 
            this.Write("\n                writer.WritePropertyName(value.value.ToString());\n");
 } 
            this.Write("\n            }\n\n            public override ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializer" +
                    "Options options)\n            {\n");
if (IsSupportUtf8Formatter()) {  
            this.Write("\n                if (System.Buffers.Text.Utf8Parser.TryParse(reader.ValueSpan, ou" +
                    "t ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" value, out var consumed))\n                {\n                    return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(value);\n                }\n                else\n                {\n               " +
                    "     return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".Parse(reader.GetString()));\n                }\n");
 } else if (IsUlid()) { 
            this.Write("\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".Parse(reader.GetString()));\n");
 } else if(Type == "string")  { 
            this.Write("\n                    return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(reader.GetString());\n");
 } else { 
            this.Write("\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".Parse(reader.GetString()));\n");
 } 
            this.Write("\n            }\n\n");
 } 
            this.Write("\n\n        }\n\n");
 } 
            this.Write("\n\n");
 if (HasFlag(UnitGenerateOptions.MessagePackFormatter)) { 
            this.Write(" \n        // UnitGenerateOptions.MessagePackFormatter\n        private class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("MessagePackFormatter : IMessagePackFormatter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(">\n        {\n            public void Serialize(ref MessagePackWriter writer, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value, MessagePackSerializerOptions options)\n            {\n                optio" +
                    "ns.Resolver.GetFormatterWithVerify<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(">().Serialize(ref writer, value.value, options);\n            }\n\n            publi" +
                    "c ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)\n" +
                    "            {\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(options.Resolver.GetFormatterWithVerify<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(">().Deserialize(ref reader, options));\n            }\n        }\n\n");
 } 
            this.Write("\n\n");
 if (HasFlag(UnitGenerateOptions.DapperTypeHandler)) { 
            this.Write(" \n        // UnitGenerateOptions.DapperTypeHandler\n        public class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("TypeHandler : Dapper.SqlMapper.TypeHandler<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(">\n        {\n            public override ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Parse(object value)\n            {\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")value);\n            }\n\n            public override void SetValue(System.Data.IDb" +
                    "DataParameter parameter, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value)\n            {\n                parameter.DbType = System.Data.DbType.");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDbType()));
            this.Write(";\n                parameter.Value = value.value;\n            }\n        }\n\n       " +
                    " [ModuleInitializer]\n        public static void AddTypeHandler()\n        {\n     " +
                    "       Dapper.SqlMapper.AddTypeHandler(new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(".");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("TypeHandler());\n        }\n");
 } 
            this.Write("\n\n");
 if (HasFlag(UnitGenerateOptions.EntityFrameworkValueConverter)) { 
            this.Write(" \n        // UnitGenerateOptions.EntityFrameworkValueConverter\n        public cla" +
                    "ss ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("ValueConverter : Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConve" +
                    "rter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(">\n        {\n            public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("ValueConverter()\n                : base(\n                        convertToProvide" +
                    "rExpression: x => x.value,\n                        convertFromProviderExpression" +
                    ": x => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(x))\n            {\n            }\n\n            public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(@"ValueConverter(Microsoft.EntityFrameworkCore.Storage.ValueConversion.ConverterMappingHints mappingHints = null)
                : base(
                        convertToProviderExpression: x => x.value,
                        convertFromProviderExpression: x => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(x),\n                        mappingHints: mappingHints)\n            {\n          " +
                    "  }\n        }\n\n");
 } 
            this.Write("\n        // Default\n        private class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("TypeConverter : System.ComponentModel.TypeConverter\n        {\n            private" +
                    " static readonly Type WrapperType = typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(");\n            private static readonly Type ValueType = typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(@");

            public override bool CanConvertFrom(System.ComponentModel.ITypeDescriptorContext context, Type sourceType)
            {
                if (sourceType == WrapperType || sourceType == ValueType)
                {
                    return true;
                }

                return base.CanConvertFrom(context, sourceType);
            }

            public override bool CanConvertTo(System.ComponentModel.ITypeDescriptorContext context, Type destinationType)
            {
                if (destinationType == WrapperType || destinationType == ValueType)
                {
                    return true;
                }

                return base.CanConvertTo(context, destinationType);
            }

            public override object ConvertFrom(System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value)
            {
                if (value != null)
                {
                    var t = value.GetType();
                    if (t == typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("))\n                    {\n                        return (");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(")value;\n                    }\n                    if (t == typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write("))\n                    {\n                        return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(@")value);
                    }
                }

                return base.ConvertFrom(context, culture, value);
            }

            public override object ConvertTo(System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value, Type destinationType)
            {
                if (value is ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(@" wrappedValue)
                {
                    if (destinationType == WrapperType)
                    {
                        return wrappedValue;
                    }

                    if (destinationType == ValueType)
                    {
                        return wrappedValue.AsPrimitive();
                    }
                }

                return base.ConvertTo(context, culture, value, destinationType);
            }
        }
    }
");
 if (!string.IsNullOrEmpty(Namespace)) { 
            this.Write("\n}\n");
 } 
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class CodeTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
