// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NullableUnitGenerator.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CodeTemplate : CodeTemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY NullableUnitGenerator. DO NOT CHANGE IT.
// </auto-generated>
#pragma warning disable CS8669  // Null 許容参照型の注釈は、'#nullable' 注釈のコンテキスト内のコードでのみ使用する必要があります。自動生成されたコードには、ソースに明示的な '#nullable' ディレクティブが必要です。
#pragma warning disable CS8632	// '#nullable' 注釈コンテキスト内のコードでのみ、Null 許容参照型の注釈を使用する必要があります。
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
");
 if (HasFlag(UnitGenerateOptions.DapperTypeHandler)) { 
            this.Write("using System.Runtime.CompilerServices;\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.JsonConverter)) { 
            this.Write("using System.Text.Json;\r\nusing System.Text.Json.Serialization;\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.MessagePackFormatter)) { 
            this.Write("using MessagePack;\r\nusing MessagePack.Formatters;\r\n");
 } 
            this.Write("\r\nusing NullableUnitGenerator;\r\n\r\n");
 if (!string.IsNullOrEmpty(Namespace)) { 
            this.Write("namespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            this.Write(";\r\n");
 } 
            this.Write("\r\n\r\n/// <summary>\r\n/// ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" is TernaryType ValueObject<br/>\r\n/// Primitive type is ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write("\r\n/// </summary>\r\n");
 if (HasFlag(UnitGenerateOptions.MessagePackFormatter)) { 
            this.Write("[MessagePackFormatter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("MessagePackFormatter))]\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.JsonConverter)) { 
            this.Write("[JsonConverter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("JsonConverter))]\r\n");
 } 
            this.Write("[System.ComponentModel.TypeConverter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("TypeConverter))]\r\nreadonly partial struct ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" : IEquatable<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(">, IEqualityComparer<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("> ");
            this.Write(this.ToStringHelper.ToStringWithCulture(HasFlag(UnitGenerateOptions.Comparable) ? $", IComparable<{Name}>" : ""));
            this.Write("\r\n{\r\n    //\r\n    // Constructor\r\n    //\r\n\r\n    /// <summary>Complete Constructor<" +
                    "/summary>\r\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value)\r\n    {\r\n        (m_state, m_value) = (value.m_state, value.m_value);\r\n\r\n");
 if (HasFlag(UnitGenerateOptions.Validate)) { 
            this.Write("        this.Validate();\r\n");
 } 
            this.Write("    }\r\n\r\n    /// <summary>Complete Constructor</summary>\r\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(in TernaryState state, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" value = default)\r\n    {\r\n        (m_state, m_value) = (state, value) switch\r\n   " +
                    "     {\r\n            (TernaryState.Undef, _) => (state, default),\r\n            (T" +
                    "ernaryState.Null, _) => (state, default),\r\n");
 if (!IsValueType) { 
            this.Write("            (_, null) => (state, default),\r\n");
 } 
            this.Write("            _ => (state, value)\r\n        };\r\n    }\r\n\r\n");
 if (IsValueType) { 
            this.Write("    /// <summary>Complete Constructor</summary>\r\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" value)\r\n    {\r\n        (m_state, m_value) = (TernaryState.Value, value);\r\n\r\n");
 if (HasFlag(UnitGenerateOptions.Validate)) { 
            this.Write("        this.Validate();\r\n");
 } 
            this.Write("    }\r\n");
 } 
            this.Write("\r\n    /// <summary>Complete Constructor</summary>\r\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(" value)\r\n    {\r\n        (m_state, m_value) = value switch\r\n        {\r\n           " +
                    " null => (TernaryState.Null, default),\r\n            _ => (TernaryState.Value, (");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")value),\r\n        };\r\n\r\n");
 if (HasFlag(UnitGenerateOptions.Validate)) { 
            this.Write("        this.Validate();\r\n");
 } 
            this.Write(@"    }


    //
    // static define
    //

    /// <summary>Display string as Undef.</summary>
    public static readonly string sUndef = $""~{TernaryState.Undef}~"";

    /// <summary>Display string as Null.</summary>
    public static readonly string sNull = $""~{TernaryState.Null}~"";


    //
    // static property
    //

    /// <summary>Undefined value instance.</summary>
    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" UndefValue { get; } = new(TernaryState.Undef, default);\r\n\r\n    /// <summary>Null" +
                    " value instance.</summary>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" NullValue { get; } = new(TernaryState.Null, default);\r\n\r\n    /// <summary>Value " +
                    "state default value instance.</summary>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" ValueStateDefaultValue { get; } = new(TernaryState.Value, default);\r\n\r\n    stati" +
                    "c readonly Type BaseType = typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(@");
    /// <summary>Get base type.</summary>
    public static Type GetBaseType() => BaseType;

    /// <summary>Is base type nullable?</summary>
    public static bool IsNullable { get; } 
        = !BaseType.IsValueType  // 値型でない -> Nullable
        || Nullable.GetUnderlyingType(BaseType) != null;  // 非Null許容型が取得できる -> Null許容演算子が指定されている -> Nullable


    //
    // static method
    //

    /// <summary>Determines if either value is undefined or null.</summary>
    /// <returns>
    /// Return Value – Description<br/>
    /// <b>TernaryState.Undef</b> – if either value is undefined.<br/>
    /// <b>TernaryState.Null</b> – if either value is null.<br/>
    /// <b>TernaryState.Value</b> – if either value is set.
    /// </returns>
    public static TernaryState CheckState(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result)\r\n    {\r\n        var (state, outVal) = (x, y) switch\r\n        {\r\n        " +
                    "    { x.IsUndef: true } => (TernaryState.Undef, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(".UndefValue),\r\n            { y.IsUndef: true } => (TernaryState.Undef, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(".UndefValue),\r\n            { x.IsNull: true } => (TernaryState.Null, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(".NullValue),\r\n            { y.IsNull: true } => (TernaryState.Null, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(".NullValue),\r\n            _ => (TernaryState.Value, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(@".ValueStateDefaultValue),
        };
        result = outVal;
        return state;
    }

    /// <summary>Determine if a value is undefined or null.</summary>
    /// <returns>
    /// Return Value – Description<br/>
    /// <b>TernaryState.Undef</b> – if value is undefined.<br/>
    /// <b>TernaryState.Null</b> – if value is null.<br/>
    /// <b>TernaryState.Value</b> – if value is set.
    /// </returns>
    public static TernaryState CheckState(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result)\r\n    {\r\n        var (state, outVal) = x switch\r\n        {\r\n            {" +
                    " IsUndef: true } => (TernaryState.Undef, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(".UndefValue),\r\n            { IsNull: true } => (TernaryState.Null, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(".NullValue),\r\n            _ => (TernaryState.Value, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(".ValueStateDefaultValue),\r\n        };\r\n        result = outVal;\r\n        return s" +
                    "tate;\r\n    }\r\n\r\n\r\n    //\r\n    // backing field\r\n    //\r\n\r\n    internal readonly " +
                    "");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" m_value = default;\r\n    internal readonly TernaryState m_state = TernaryState.Un" +
                    "def;\r\n\r\n\r\n    //\r\n    // get state\r\n    //\r\n\r\n    /// <summary><see langword=\"tr" +
                    "ue\"/> if undefined; otherwise, <see langword=\"false\"/>.</summary>\r\n    /// <retu" +
                    "rns><b><see langword=\"true\"/></b> : if undefined</returns>\r\n    public bool IsUn" +
                    "def\r\n        => m_state == TernaryState.Undef;\r\n\r\n    /// <summary><see langword" +
                    "=\"true\"/> if null; otherwise, <see langword=\"false\"/>.</summary>\r\n    /// <retur" +
                    "ns><b><see langword=\"true\"/></b> : if null</returns>\r\n    public bool IsNull\r\n  " +
                    "      => m_state == TernaryState.Null;\r\n\r\n    /// <summary><see langword=\"true\"/" +
                    "> if undefined or null; otherwise, <see langword=\"false\"/>.</summary>\r\n    /// <" +
                    "returns><b><see langword=\"true\"/></b> : if null or undefined</returns>\r\n    publ" +
                    "ic bool IsUndefOrNull\r\n        => m_state != TernaryState.Value;\r\n\r\n    /// <sum" +
                    "mary><see langword=\"true\"/> if not undefined and not null; otherwise, <see langw" +
                    "ord=\"false\"/>.</summary>\r\n    /// <returns><b><see langword=\"true\"/></b> : if no" +
                    "t undefined and not null</returns>\r\n    public bool HasValue\r\n        => m_state" +
                    " == TernaryState.Value;\r\n\r\n    /// <summary>return value state.</summary>\r\n    /" +
                    "// <returns>\r\n    /// <b>Undef</b><br/>\r\n    /// <b>Null</b><br/>\r\n    /// <b>Va" +
                    "lue</b>\r\n    /// </returns>\r\n    public TernaryState State\r\n        => m_state;\r" +
                    "\n\r\n\r\n    //\r\n    // get value\r\n    //\r\n\r\n    /// <summary>return value if HasVal" +
                    "ue is true; otherwise, throw InvalidOperationException()</summary>\r\n    /// <ret" +
                    "urns>\r\n    /// <b>value</b> : if HasValue is true<br/>\r\n    /// <b>throw Invalid" +
                    "OperationException(\"Value is Null.\")</b> : if IsNull is true<br/>\r\n    /// <b>th" +
                    "row InvalidOperationException(\"Value is Undef.\")</b> : if IsUndef is true\r\n    /" +
                    "// </returns>\r\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" Value\r\n        => GetOrThrow();\r\n\r\n    /// <inheritdoc cref=\"Value\" />\r\n    publ" +
                    "ic ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" AsPrimitive()\r\n        => Value;\r\n\r\n    /// <summary>return raw value</summary>\r" +
                    "\n    /// <returns>inner raw value</returns>\r\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(@"  GetRawValue()
        => m_value;

    /// <summary>return value if HasValue is true; otherwise, defaultValue</summary>
    /// <returns>
    /// <b>value</b> : if assigned and not null<br/>
    /// <b>defaultValue</b> : otherwise
    /// </returns>
    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" GetOr(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" defaultValue)\r\n        => HasValue ? m_value : defaultValue;\r\n\r\n");
 if (IsValueType) { 
            this.Write("    /// <inheritdoc cref=\"GetOr\" />\r\n    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(" GetOr(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(" defaultValue)\r\n        => HasValue ? m_value : defaultValue;\r\n");
 } 
            this.Write(@"
    /// <summary>return value if HasValue is true; otherwise, <see langword=""default""/></summary>
    /// <returns>
    /// <b>value</b> : if assigned and not null<br/>
    /// <b><see langword=""default""/></b> : otherwise
    /// </returns>
    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(@" GetOrDefault()
        => GetOr(default);

    /// <summary>return value if HasValue is true; otherwise, <see langword=""null""/></summary>
    /// <returns>
    /// <b>value</b> : if assigned and not null<br/>
    /// <b><see langword=""null""/></b> : otherwise
    /// </returns>
    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(" GetOrNull()\r\n        => GetOr(null);\r\n\r\n    /// <inheritdoc cref=\"Value\" />\r\n   " +
                    " public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(@" GetOrThrow()
        => (m_state, m_value) switch
        {
            (TernaryState.Value, _) => m_value,
            (TernaryState.Null, _) => throw new InvalidOperationException($""Value is {TernaryState.Null}.""),
            _ => throw new InvalidOperationException($""Value is {TernaryState.Undef}.""),
        };

    /// <summary>return true and out parameter value if HasValue is true; otherwise, false.</summary>
    /// <param name=""value"">value</param>
    /// <param name=""defaultValue"">defaultValue</param>
    /// <returns><b><see langword=""true""/> and out parameter value</b> : if HasValue is true,</returns>
    public bool TryGet(out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" value, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" defaultValue = default)\r\n    {\r\n        value = HasValue ? m_value : defaultValu" +
                    "e;\r\n        return HasValue;\r\n    }\r\n\r\n");
 if (HasFlag(UnitGenerateOptions.Validate)) { 
            this.Write("\r\n    //\r\n    // Validate\r\n    //\r\n\r\n    /// <summary>Validate</summary>\r\n    pri" +
                    "vate partial void Validate();\r\n\r\n");
 } 
            this.Write("\r\n    //\r\n    // GetHashCode\r\n    //\r\n\r\n    /// <inheritdoc/>\r\n    public overrid" +
                    "e int GetHashCode()\r\n        => (m_state, m_value).GetHashCode();\r\n\r\n    /// <in" +
                    "heritdoc/>\r\n    public int GetHashCode(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(@" obj)
        => (obj.m_state, obj.m_value).GetHashCode();


    //
    // ToString
    //

    /// <summary>Returns this instance of System.String; no actual conversion is performed.</summary>
    /// <returns>The current string.</returns>
    public override string ToString()
");
 if (ToStringFormat == null) { 
            this.Write("        => ValueString;\r\n");
 } else { 
            this.Write("        => HasValue ? string.Format(\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(ToStringFormat));
            this.Write("\", m_value) : (IsNull ? sNull : sUndef);\r\n");
 } 
            this.Write(@"
    /// <summary>return value string.</summary>
    /// <returns>
    /// <b>ValueString</b> : if HasValue is true<br/>
    /// <b>""~Null~""</b> : if IsNull is true<br/>
    /// <b>""~Undef~""</b> : if IsUndefined is true
    /// </returns>
    string ValueString
        => HasValue ? $""{m_value}"" : (IsNull ? sNull : sUndef);


    //
    // implicit, explicit operator
    //

    /// <summary>explicit(明示的) operator</summary>
    public static explicit operator ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write("(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value)\r\n        => (");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")value.GetOrThrow();\r\n\r\n    /// <summary>");
            this.Write(this.ToStringHelper.ToStringWithCulture(HasFlag(UnitGenerateOptions.ImplicitOperator) ? "implicit(暗黙的)" : "explicit(明示的)"));
            this.Write(" operator</summary>\r\n    /// <returns>");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value.</returns>\r\n    public static implicit operator ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" value)\r\n        => new(value);\r\n\r\n");
 if (IsValueType) { 
            this.Write("    /// <summary>explicit(明示的) operator</summary>\r\n    /// <returns>");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(" value.</returns>\r\n    public static explicit operator ");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write("(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value)\r\n        => (");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(")value.GetOrNull();\r\n\r\n    /// <summary>");
            this.Write(this.ToStringHelper.ToStringWithCulture(HasFlag(UnitGenerateOptions.ImplicitOperator) ? "implicit(暗黙的)" : "explicit(明示的)"));
            this.Write(" operator</summary>\r\n    /// <returns>");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value.</returns>\r\n    public static implicit operator ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(" value)\r\n        => new(value);\r\n\r\n");
 } 
            this.Write("\r\n    //\r\n    // Equals, IEquatable<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(">\r\n    //\r\n\r\n    /// <inheritdoc/>\r\n    public bool Equals(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" other)\r\n        => m_state.Equals(other.m_state) && m_value.Equals(other.m_value" +
                    ");\r\n        \r\n    /// <inheritdoc/>\r\n    public bool Equals(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        => x.Equals(y);\r\n\r\n    /// <inheritdoc/>\r\n    public override bool E" +
                    "quals(object? obj)\r\n        => obj is ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(@" ts && Equals(ts);


    //
    // ==, != operator
    //

    /// <summary>Returns a value indicating whether two instances are same value.</summary>
    /// <returns>true if other has the same value as this instance; otherwise, false.</returns>
    public static bool operator ==(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(@" y)
        => x.Equals(y);

    /// <summary>Returns a value indicates whether two instances are different values.</summary>
    /// <returns>true if other has the same value as this instance; otherwise, false.</returns>
    public static bool operator !=(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        => !(x == y);\r\n\r\n");
 if (HasFlag(UnitGenerateOptions.Comparable)) { 
            this.Write("\r\n    //\r\n    // CompareTo, IComparable<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(">    // UnitGenerateOptions.Comparable\r\n    //\r\n\r\n    /// <summary>Compares this " +
                    "instance to a specified ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(@" and returns an indication of their relative values.</summary>
    /// <returns>
    /// A signed number indicating the relative values of this instance and value.<br/>
    /// <b>Return Value</b> – Description<br/>
    /// <b>Less than zero</b> – This instance is less than value.<br/>
    /// <b>Zero</b> – This instance is equal to value.<br/>
    /// <b>Greater than zero</b> – This instance is greater than value.
    /// </returns>
    public int CompareTo(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" other)\r\n        => CheckState(this, other, out _) == TernaryState.Value\r\n       " +
                    "    ? m_value.CompareTo(other.m_value)\r\n           : 0;\r\n\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.Comparable) && !HasFlag(UnitGenerateOptions.WithoutComparisonOperator)) { 
            this.Write("\r\n    //\r\n    // >, <, >=, <= operator    // UnitGenerateOptions.Comparable and W" +
                    "ithoutComparisonOperator\r\n    //\r\n\r\n    /// <summary>operator &gt;</summary>\r\n  " +
                    "  public static bool operator >(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        => CheckState(x, y, out _) == TernaryState.Value\r\n            ? x.m_" +
                    "value > y.m_value\r\n            : false;\r\n\r\n    /// <summary>operator &lt;</summa" +
                    "ry>\r\n    public static bool operator <(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        => CheckState(x, y, out _) == TernaryState.Value\r\n            ? x.m_" +
                    "value < y.m_value\r\n            : false;\r\n\r\n    /// <summary>operator &gt;=</summ" +
                    "ary>\r\n    public static bool operator >=(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        => CheckState(x, y, out _) == TernaryState.Value\r\n            ? x.m_" +
                    "value >= y.m_value\r\n            : false;\r\n\r\n    /// <summary>operator &lt;=</sum" +
                    "mary>\r\n    public static bool operator <=(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        => CheckState(x, y, out _) == TernaryState.Value\r\n            ? x.m_" +
                    "value <= y.m_value\r\n            : false;\r\n\r\n");
 } 
 if (Type == "Guid" || Type == "System.Guid") { 
            this.Write("\r\n    //\r\n    // Guid\r\n    //\r\n\r\n    /// <summary>NewGuid</summary>\r\n    /// <ret" +
                    "urns>Guid.NewGuid()</returns>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" New()\r\n        => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Guid.NewGuid());\r\n\r\n    /// <inheritdoc cref=\"New()\" />\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" New");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("()\r\n        => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Guid.NewGuid());\r\n\r\n");
 } 
if (IsIntegralNumericType()) { 
            this.Write("\r\n    //\r\n    // MaxValue, MinValue\r\n    //\r\n\r\n    /// <summary>Represents the la" +
                    "rgest possible value. This field is constant.</summary>\r\n    public const ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" MaxValue = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".MaxValue;\r\n\r\n    /// <summary>Represents the smallest possible value. This field" +
                    " is constant.</summary>\r\n    public const ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" MinValue = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".MinValue;\r\n\r\n");
 } 
 if (Type == "Ulid" || Type == "System.Ulid") { 
            this.Write("\r\n    //\r\n    // Ulid\r\n    //\r\n\r\n    /// <summary>NewUlid</summary>\r\n    /// <ret" +
                    "urns>Ulid.NewUlid()</returns>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" New()\r\n        => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Ulid.NewUlid());\r\n\r\n    /// <inheritdoc cref=\"New()\" />\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" New");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("()\r\n        => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Ulid.NewUlid());\r\n\r\n");
 } 
            this.Write("\r\n");
 if (HasFlag(UnitGenerateOptions.ParseMethod)) { 
            this.Write(@"
    //
    // Parse, TryParse    // UnitGenerateOptions.ParseMethod
    //

    /// <summary>Converts the string representation of a number.</summary>
    /// <returns>A equivalent to the number contained in s.</returns>
    /// <exception cref=""System.ArgumentNullException"" >s is null.</exception>
    /// <exception cref=""System.FormatException"" >is not in the correct format.</exception>
    /// <exception cref=""System.OverflowException"" >s represents a number less than MinValue or greater than MaxValue.</exception>
    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Parse(string s)\r\n");
 if (Type == "string") { 
            this.Write("        => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(s);\r\n\r\n");
 } else { 
            this.Write("        => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".Parse(s));\r\n\r\n");
 } 
            this.Write(@"    /// <summary>Converts the string representation of a number. A return value indicates whether the conversion succeeded.</summary>
    /// <returns>true if s was converted successfully; otherwise, false.</returns>
    public static bool TryParse(string s, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result)\r\n    {\r\n");
 if (Type == "string") { 
            this.Write("        try\r\n        {\r\n            result = Parse(s);\r\n            return true;\r" +
                    "\n        }\r\n        catch\r\n        {\r\n            result = NullValue;\r\n         " +
                    "   return false;\r\n        }\r\n");
 } else { 
            this.Write("        if(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".TryParse(s, out var r))\r\n        {\r\n            result = new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(r);\r\n            return true;\r\n        }\r\n        else\r\n        {\r\n            r" +
                    "esult = NullValue;\r\n            return false;\r\n        }\r\n");
 } 
            this.Write("    }\r\n\r\n");
 } 
            this.Write("\r\n");
 if (HasFlag(UnitGenerateOptions.MinMaxMethod)) { 
            this.Write("\r\n    //\r\n    // UnitGenerateOptions.MinMaxMethod\r\n    //\r\n\r\n    /// <summary>Min" +
                    "</summary>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Min(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        => CheckState(x, y, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Math.Max(x.m_value, y.m_value))\r\n            : result;\r\n\r\n    /// <summary>Max</" +
                    "summary>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Max(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        => CheckState(x, y, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Math.Max(x.m_value, y.m_value))\r\n            : result;\r\n\r\n");
 } 
 if (Type == "bool") { 
            this.Write("\r\n    //\r\n    // bool operator\r\n    //\r\n\r\n    /// <summary>operator true</summary" +
                    ">\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" operator true(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\r\n        => CheckState(x, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? x.m_value\r\n            : result;\r\n\r" +
                    "\n    /// <summary>operator false</summary>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" operator false(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\r\n        => CheckState(x, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? !x.m_value\r\n            : result;\r\n" +
                    "\r\n    /// <summary>operator !</summary>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" operator !(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\r\n        => CheckState(x, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? !x.m_value\r\n            : result;\r\n" +
                    "\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.ArithmeticOperator)) { 
            this.Write("\r\n    //\r\n    // +, -, *, /, % operator    UnitGenerateOptions.ArithmeticOperator" +
                    "\r\n    //\r\n\r\n    /// <summary>operator +</summary>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator +(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        => CheckState(x, y, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(checked ((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.m_value + y.m_value)))\r\n            : result;\r\n\r\n    /// <summary>operator -<" +
                    "/summary>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator -(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        => CheckState(x, y, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(checked ((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.m_value - y.m_value)))\r\n            : result;\r\n\r\n    /// <summary>operator *<" +
                    "/summary>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator *(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        => CheckState(x, y, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(checked ((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.m_value * y.m_value)))\r\n            : result;\r\n\r\n    /// <summary>operator /<" +
                    "/summary>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator /(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        => CheckState(x, y, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(checked ((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.m_value / y.m_value)))\r\n            : result;\r\n\r\n    /// <summary>operator %<" +
                    "/summary>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator %(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        => CheckState(x, y, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(checked ((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.m_value % y.m_value)))\r\n            : result;\r\n\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.ValueArithmeticOperator)) { 
            this.Write("\r\n    //\r\n    // ++, --, +, -, *, /, % operator    UnitGenerateOptions.ValueArith" +
                    "meticOperator\r\n    //\r\n\r\n    /// <summary>operator ++</summary>\r\n    public stat" +
                    "ic ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator ++(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\r\n        => CheckState(x, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(checked ((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.m_value + 1)))\r\n            : result;\r\n\r\n    /// <summary>operator --</summar" +
                    "y>\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator --(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\r\n        => CheckState(x, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(checked ((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.m_value - 1)))\r\n            : result;\r\n\r\n    /// <summary>operator +</summary" +
                    ">\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator +(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" y)\r\n        => CheckState(x, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(checked ((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.m_value + y)))\r\n            : result;\r\n\r\n    /// <summary>operator -</summary" +
                    ">\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator -(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" y)\r\n        => CheckState(x, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(checked ((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.m_value - y)))\r\n            : result;\r\n\r\n    /// <summary>operator *</summary" +
                    ">\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator *(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" y)\r\n        => CheckState(x, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(checked ((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.m_value * y)))\r\n            : result;\r\n\r\n    /// <summary>operator /</summary" +
                    ">\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator /(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" y)\r\n        => CheckState(x, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(checked ((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.m_value / y)))\r\n            : result;\r\n\r\n    /// <summary>operator %</summary" +
                    ">\r\n    public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator %(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" y)\r\n        => CheckState(x, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result) == TernaryState.Value\r\n            ? new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(checked ((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.m_value % y)))\r\n            : result;\r\n\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.JsonConverter)) { 
            this.Write("\r\n    //\r\n    // UnitGenerateOptions.JsonConverter\r\n    //\r\n\r\n    /// <summary>Js" +
                    "onConverter</summary>\r\n    private class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("JsonConverter : JsonConverter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(">\r\n    {\r\n        /// <summary>HandleNull</summary>\r\n        public override bool" +
                    " HandleNull\r\n            => true;\r\n\r\n        /// <summary>Write</summary>\r\n     " +
                    "   public override void Write(Utf8JsonWriter writer, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value, JsonSerializerOptions options)\r\n        {\r\n            // undefined; valu" +
                    "e.IsUndefined の場合は key,value ともに書き込まない\r\n            if (value.IsUndef)\r\n        " +
                    "        return;\r\n\r\n            var converter = options.GetConverter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(")) as JsonConverter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(">;\r\n            if (converter is not null)\r\n                converter.Write(write" +
                    "r, (");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(")value.GetOrNull(), options);\r\n            else\r\n                throw new JsonEx" +
                    "ception($\"{typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(")} converter does not found.\");\r\n        }\r\n\r\n        /// <summary>Read</summary>" +
                    "\r\n        public override ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions option" +
                    "s)\r\n        {\r\n            var converter = options.GetConverter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(")) as JsonConverter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(">;\r\n            if (converter is not null)\r\n            {\r\n                var re" +
                    "s = (reader.TokenType) switch\r\n                {\r\n                    JsonTokenT" +
                    "ype.Null => ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(".NullValue,\r\n                    JsonTokenType.None => ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(".UndefValue,\r\n                    _ => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(converter.Read(ref reader, typeToConvert, options))\r\n                };\r\n       " +
                    "         return res;\r\n            }\r\n            else\r\n            {\r\n          " +
                    "      throw new JsonException($\"{typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(")} converter does not found.\");\r\n            }\r\n        }\r\n\r\n");
if (HasFlag(UnitGenerateOptions.JsonConverterDictionaryKeySupport)) {  
            this.Write("        /// <summary>WriteAsPropertyName</summary>\r\n        public override void " +
                    "WriteAsPropertyName(Utf8JsonWriter writer, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value, JsonSerializerOptions options)\r\n        {\r\n");
if (IsSupportUtf8Formatter()) {  
            this.Write(@"            Span<byte> buffer = stackalloc byte[36];
            if (System.Buffers.Text.Utf8Formatter.TryFormat(value.m_value, buffer, out var written))
            {
                writer.WritePropertyName(buffer.Slice(0, written));
            }
            else
            {
                writer.WritePropertyName(value.m_value.ToString());
            }
");
 } else if (IsUlid()) { 
            this.Write("            writer.WritePropertyName(value.m_value.ToString());\r\n");
 } else { 
            this.Write("            writer.WritePropertyName(value.m_value.ToString());\r\n");
 } 
            this.Write("        }\r\n\r\n        /// <summary>ReadAsPropertyName</summary>\r\n        public ov" +
                    "erride ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializer" +
                    "Options options)\r\n        {\r\n");
if (IsSupportUtf8Formatter()) {  
            this.Write("            if (System.Buffers.Text.Utf8Parser.TryParse(reader.ValueSpan, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" value, out var consumed))\r\n            {\r\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(value);\r\n            }\r\n            else\r\n            {\r\n                return " +
                    "new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".Parse(reader.GetString()));\r\n            }\r\n");
 } else if (IsUlid()) { 
            this.Write("            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".Parse(reader.GetString()));\r\n");
 } else if(Type == "string")  { 
            this.Write("                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(reader.GetString());\r\n");
 } else { 
            this.Write("            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".Parse(reader.GetString()));\r\n");
 } 
            this.Write("        }\r\n");
 } 
            this.Write("    }\r\n\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.MessagePackFormatter)) { 
            this.Write("\r\n    //\r\n    // UnitGenerateOptions.MessagePackFormatter\r\n    //\r\n\r\n    /// <sum" +
                    "mary>IMessagePackFormatter</summary>\r\n    private class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("MessagePackFormatter : IMessagePackFormatter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(">\r\n    {\r\n        /// <summary>Serialize</summary>\r\n        public void Serialize" +
                    "(ref MessagePackWriter writer, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value, MessagePackSerializerOptions options)\r\n        {\r\n            options.Res" +
                    "olver.GetFormatterWithVerify<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(">().Serialize(ref writer, value.m_value, options);\r\n        }\r\n\r\n        /// <sum" +
                    "mary>Deserialize</summary>\r\n        public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)\r" +
                    "\n        {\r\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(options.Resolver.GetFormatterWithVerify<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(">().Deserialize(ref reader, options));\r\n        }\r\n    }\r\n\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.DapperTypeHandler)) { 
            this.Write("\r\n    //\r\n    // UnitGenerateOptions.DapperTypeHandler\r\n    //\r\n\r\n    /// <summar" +
                    "y>Dapper.SqlMapper.TypeHandler</summary>\r\n    public class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("TypeHandler : Dapper.SqlMapper.TypeHandler<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(">\r\n    {\r\n        /// <summary>Parse</summary>\r\n        public override ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Parse(object value)\r\n        {\r\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(")value);\r\n        }\r\n\r\n        /// <summary>SetValue</summary>\r\n        public ov" +
                    "erride void SetValue(System.Data.IDbDataParameter parameter, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value)\r\n        {\r\n            parameter.DbType = System.Data.DbType.");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDbType()));
            this.Write(";\r\n            parameter.Value = (");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(")value.GetOrNull();\r\n        }\r\n    }\r\n\r\n    /// <summary>Dapper.SqlMapper.AddTyp" +
                    "eHandler</summary>\r\n    [ModuleInitializer]\r\n    public static void AddTypeHandl" +
                    "er()\r\n    {\r\n        Dapper.SqlMapper.AddTypeHandler(new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(".");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("TypeHandler());\r\n    }\r\n\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.EntityFrameworkValueConverter)) { 
            this.Write("\r\n    //\r\n    // UnitGenerateOptions.EntityFrameworkValueConverter\r\n    //\r\n\r\n   " +
                    " /// <summary>Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConvert" +
                    "er</summary>\r\n    public class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("ValueConverter : Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConve" +
                    "rter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(">\r\n    {\r\n        /// <summary>ValueConverter</summary>\r\n        public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("ValueConverter()\r\n            : base(\r\n                    convertToProviderExpre" +
                    "ssion: x => (");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(")x.GetOrNull(),\r\n                    convertFromProviderExpression: x => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(x))\r\n        {\r\n        }\r\n\r\n        /// <summary>ValueConverter</summary>\r\n    " +
                    "    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("ValueConverter(Microsoft.EntityFrameworkCore.Storage.ValueConversion.ConverterMap" +
                    "pingHints mappingHints = null)\r\n            : base(\r\n                    convert" +
                    "ToProviderExpression: x => (");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeNullable));
            this.Write(")x.GetOrNull(),\r\n                    convertFromProviderExpression: x => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(x),\r\n                    mappingHints: mappingHints)\r\n        {\r\n        }\r\n    " +
                    "}\r\n\r\n");
 } 
            this.Write("\r\n    //\r\n    // TypeConverter\r\n    //\r\n\r\n    /// <summary>System.ComponentModel." +
                    "TypeConverter</summary>\r\n    private class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("TypeConverter : System.ComponentModel.TypeConverter\r\n    {\r\n        private stati" +
                    "c readonly Type WrapperType = typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(");\r\n        private static readonly Type ValueType = typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(@");

        /// <summary>CanConvertFrom</summary>
        public override bool CanConvertFrom(System.ComponentModel.ITypeDescriptorContext? context, Type sourceType)
        {
            if (sourceType == WrapperType || sourceType == ValueType)
            {
                return true;
            }

            return base.CanConvertFrom(context, sourceType);
        }

        /// <summary>CanConvertTo</summary>
        public override bool CanConvertTo(System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType)
        {
            if (destinationType == WrapperType || destinationType == ValueType)
            {
                return true;
            }

            return base.CanConvertTo(context, destinationType);
        }

        /// <summary>ConvertFrom</summary>
        public override object? ConvertFrom(System.ComponentModel.ITypeDescriptorContext? context, System.Globalization.CultureInfo? culture, object value)
        {
            if (value != null)
            {
                var t = value.GetType();
                if (t == typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("))\r\n                {\r\n                    return (");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(")value;\r\n                }\r\n                if (t == typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write("))\r\n                {\r\n                    return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")value);\r\n                }\r\n            }\r\n            else\r\n            {\r\n    " +
                    "            return ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(@".NullValue;
            }

            return base.ConvertFrom(context, culture, value);
        }

        /// <summary>ConvertTo</summary>
        public override object? ConvertTo(System.ComponentModel.ITypeDescriptorContext? context, System.Globalization.CultureInfo? culture, object? value, Type destinationType)
        {
            if (value is ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(@" wrappedValue)
            {
                if (destinationType == WrapperType)
                {
                    return wrappedValue;
                }

                if (destinationType == ValueType)
                {
                    return wrappedValue.GetOrNull();
                }
            }

            return base.ConvertTo(context, culture, value, destinationType);
        }
    }
}
");
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class CodeTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
