# push されたら UnitTest.

name: build
on: [push, pull_request]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  DOTNET_VERSION: 6.0.x
  DOTNET_TFM: netstandard2.0
  REF_NAME: ${{ github.ref_name }}
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.0
    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Build
      # run: dotnet build -f ${{ env.DOTNET_TFM }} -c Release
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build
